/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package custserviceman;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author user
 */
public class ManageBooking extends javax.swing.JInternalFrame {

    Connection con=null;
    PreparedStatement pst=null;
    PreparedStatement pst1=null,pst2=null,pst3=null,pst4=null;
    ResultSet rs=null,rs2=null;
    
    /**
     * Creates new form ManageBooking
     */
    public ManageBooking() {
        initComponents();
        con=mycode.DBconnect.connect();
        
        updateTableLoad();
        servicePricesTableLoad();
    }

    
    public void updateTableLoad(){
        try{
            String s34="Select * from bookings";
            pst3=con.prepareStatement(s34);
            rs2=pst3.executeQuery();
            
            jTable2.setModel(DbUtils.resultSetToTableModel(rs2));
        }
        catch(Exception e){
            
        }
    }
    
    public void servicePricesTableLoad()
            {
                try{
                    String s="Select * from serviceprices";
                    pst=con.prepareStatement(s);
                    rs=pst.executeQuery();
                    
                    jTable3.setModel(DbUtils.resultSetToTableModel(rs));
                }
                catch(Exception e)
                {
                    
                }
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCustID = new javax.swing.JTextField();
        txtCustName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtVehiModel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chkCarwash = new javax.swing.JCheckBox();
        chkFullLub = new javax.swing.JCheckBox();
        chkAoutoDet = new javax.swing.JCheckBox();
        chkWhelAl = new javax.swing.JCheckBox();
        chkWheelBal = new javax.swing.JCheckBox();
        chkTyrerm = new javax.swing.JCheckBox();
        chkFullDet = new javax.swing.JCheckBox();
        chkIntDet = new javax.swing.JCheckBox();
        chkExtDet = new javax.swing.JCheckBox();
        chkStdDet = new javax.swing.JCheckBox();
        chkseatSh = new javax.swing.JCheckBox();
        chkLeathCeat = new javax.swing.JCheckBox();
        chkRep = new javax.swing.JCheckBox();
        chkPaint = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtVehinum = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        CustomerName = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        chkCarwash1 = new javax.swing.JCheckBox();
        chkTyrerm1 = new javax.swing.JCheckBox();
        chkseatSh1 = new javax.swing.JCheckBox();
        chkAoutoDet1 = new javax.swing.JCheckBox();
        chkIntDet1 = new javax.swing.JCheckBox();
        chkRep1 = new javax.swing.JCheckBox();
        chkWheelBal1 = new javax.swing.JCheckBox();
        chkCarwash2 = new javax.swing.JCheckBox();
        chkTyrerm2 = new javax.swing.JCheckBox();
        chkseatSh2 = new javax.swing.JCheckBox();
        chkAoutoDet2 = new javax.swing.JCheckBox();
        chkIntDet2 = new javax.swing.JCheckBox();
        chkRep2 = new javax.swing.JCheckBox();
        chkWheelBal2 = new javax.swing.JCheckBox();
        chkCarwash3 = new javax.swing.JCheckBox();
        chkTyrerm3 = new javax.swing.JCheckBox();
        chkseatSh3 = new javax.swing.JCheckBox();
        chkAoutoDet3 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(1030, 630));
        setMinimumSize(new java.awt.Dimension(1030, 630));
        setPreferredSize(new java.awt.Dimension(1030, 630));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1030, 630));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1030, 630));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Add New Booking");

        jLabel2.setText("Customer Id                        ");

        jLabel3.setText("Customer/Company Name  ");

        txtCustID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustIDActionPerformed(evt);
            }
        });

        txtCustName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCustNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCustNameMouseEntered(evt);
            }
        });

        jLabel4.setText("Vehicle Number                   ");

        jLabel5.setText("Vehicle Model                      ");

        jLabel6.setText("Date of Booking                  ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Service Specification");

        chkCarwash.setText("Car Wash");

        chkFullLub.setText("Full Lubricant Service");

        chkAoutoDet.setText("Auto Detailing");

        chkWhelAl.setText("Wheel Alignment");

        chkWheelBal.setText("Wheel Blanacing");

        chkTyrerm.setText("Tyre Remove");

        chkFullDet.setText("Full Detail");

        chkIntDet.setText("Interior Detail");

        chkExtDet.setText("Exterior Detail");

        chkStdDet.setText("Standard Detail");
        chkStdDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkStdDetActionPerformed(evt);
            }
        });

        chkseatSh.setText("Seat Shampooing");

        chkLeathCeat.setText("Leather Seat Care");

        chkRep.setText("Repairs");

        chkPaint.setText("Painting");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Add Booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Book ID", "CustomerID", "CustomerName", "BookingDate", "VehicleNumber", "VehicleModel"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton6.setText("Get Previous Bookings");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtVehinum, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCustID, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtVehiModel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkCarwash)
                                            .addComponent(chkTyrerm)
                                            .addComponent(chkseatSh)
                                            .addComponent(chkRep)
                                            .addComponent(chkIntDet)
                                            .addComponent(chkAoutoDet)
                                            .addComponent(chkWheelBal))
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButton2)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(chkFullLub)
                                                    .addComponent(chkFullDet)
                                                    .addComponent(chkLeathCeat)
                                                    .addComponent(chkWhelAl)
                                                    .addComponent(chkExtDet)
                                                    .addComponent(chkPaint)))
                                            .addComponent(chkStdDet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(314, 314, 314))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustID, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txtVehinum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVehiModel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkCarwash)
                            .addComponent(chkFullLub))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkTyrerm)
                            .addComponent(chkFullDet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkseatSh)
                            .addComponent(chkLeathCeat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(chkAoutoDet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkIntDet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkRep))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(chkWhelAl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkExtDet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkPaint)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkWheelBal)
                            .addComponent(chkStdDet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Add a New Booking", jPanel1);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Service Prices View");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Service No", "Service", "Price", "Discount Amount"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 243, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("View Service Prices", jPanel2);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Booking Details");

        jLabel13.setText("Booking ID                        ");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel15.setText("Vehicle Number            ");

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jLabel16.setText("Vehicle Model              ");

        jLabel17.setText("Date        ");

        jCheckBox15.setText("Car Wash");

        jCheckBox16.setText("Tyre Remove");

        jCheckBox17.setText("Seat Shampooing");

        jCheckBox18.setText("Full Lubricant Service");

        jCheckBox19.setText("Full Detail");

        jCheckBox20.setText("Leather Seat Care");

        jCheckBox21.setText("Auto Detailing");

        jCheckBox22.setText("Interior Detail");

        jCheckBox23.setText("Repairs");

        jCheckBox26.setText("Painting");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Update Booking");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Booking ID", "VehicleNo", "VehicleModel", "Date", "carwash", "tyreRem", "seatShamp", "fullLubService", "fuulDetail", "leatherSeatCar", "autoDet", "intDtail", "repairs", "wheelAli", "extDetail", "painting", "wheelBal", "stdDet"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel18.setText("CustomerId           ");

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        CustomerName.setText("CustomerName    ");

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        chkCarwash1.setText("Car Wash");

        chkTyrerm1.setText("Tyre Remove");

        chkseatSh1.setText("Seat Shampooing");

        chkAoutoDet1.setText("Auto Detailing");

        chkIntDet1.setText("Interior Detail");

        chkRep1.setText("Repairs");

        chkWheelBal1.setText("Wheel Blanacing");

        chkCarwash2.setText("Car Wash");

        chkTyrerm2.setText("Tyre Remove");

        chkseatSh2.setText("Seat Shampooing");

        chkAoutoDet2.setText("Auto Detailing");

        chkIntDet2.setText("Interior Detail");

        chkRep2.setText("Repairs");

        chkWheelBal2.setText("Wheel Blanacing");

        chkCarwash3.setText("Car Wash");

        chkTyrerm3.setText("Tyre Remove");

        chkseatSh3.setText("Seat Shampooing");

        chkAoutoDet3.setText("Auto Detailing");

        jCheckBox24.setText("Car Wash");

        jCheckBox25.setText("Tyre Remove");

        jCheckBox27.setText("Seat Shampooing");

        jCheckBox28.setText("Full Lubricant Service");

        jCheckBox29.setText("Full Detail");

        jCheckBox30.setText("Leather Seat Care");

        jCheckBox1.setText("Car Wash");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Seat Shmpoo");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Full Lubricant Service");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("tyreRemoval");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setText("Full Detail");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setText("Auto Detail");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setText("Leather Seat Care");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox8.setText("Interior detail");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox9.setText("Repairs");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        jCheckBox10.setText("Wheel Alignment");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });

        jCheckBox11.setText("Exterior Detail");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });

        jCheckBox12.setText("Painting");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });

        jCheckBox13.setText("Wheel Balancing");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });

        jCheckBox14.setText("Standard Detail");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel19.setText("BID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox1)
                                            .addComponent(jCheckBox3)
                                            .addComponent(jCheckBox2)
                                            .addComponent(jCheckBox4)
                                            .addComponent(jCheckBox5)
                                            .addComponent(jCheckBox7)
                                            .addComponent(jCheckBox6))
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox9)
                                            .addComponent(jCheckBox8)
                                            .addComponent(jCheckBox10)
                                            .addComponent(jCheckBox11)
                                            .addComponent(jCheckBox12)
                                            .addComponent(jCheckBox13)
                                            .addComponent(jCheckBox14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox15)
                                            .addComponent(jCheckBox16)
                                            .addComponent(jCheckBox17))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox18)
                                            .addComponent(jCheckBox19)
                                            .addComponent(jCheckBox20))
                                        .addGap(65, 65, 65)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox26)
                                    .addComponent(jCheckBox23)
                                    .addComponent(jCheckBox22)
                                    .addComponent(jCheckBox21))
                                .addGap(1025, 1025, 1025))))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(1262, 1262, 1262)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkCarwash1)
                        .addComponent(chkTyrerm1)
                        .addComponent(chkseatSh1)
                        .addComponent(chkRep1)
                        .addComponent(chkIntDet1)
                        .addComponent(chkAoutoDet1)
                        .addComponent(chkWheelBal1))
                    .addContainerGap(1253, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(1263, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkCarwash2)
                        .addComponent(chkTyrerm2)
                        .addComponent(chkseatSh2)
                        .addComponent(chkRep2)
                        .addComponent(chkIntDet2)
                        .addComponent(chkAoutoDet2)
                        .addComponent(chkWheelBal2))
                    .addGap(1252, 1252, 1252)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(1262, 1262, 1262)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkCarwash3)
                        .addComponent(chkTyrerm3)
                        .addComponent(chkseatSh3)
                        .addComponent(chkAoutoDet3))
                    .addContainerGap(1253, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(1194, 1194, 1194)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox24)
                        .addComponent(jCheckBox25)
                        .addComponent(jCheckBox27))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox28)
                        .addComponent(jCheckBox29)
                        .addComponent(jCheckBox30))
                    .addGap(1194, 1194, 1194)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox15)
                                    .addComponent(jCheckBox21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox16)
                                    .addComponent(jCheckBox22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox17)
                                    .addComponent(jCheckBox23)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jCheckBox18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox4)
                                .addGap(3, 3, 3)
                                .addComponent(jCheckBox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(jCheckBox7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox6)
                                .addGap(139, 139, 139))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jCheckBox9)
                                        .addGap(3, 3, 3)
                                        .addComponent(jCheckBox10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox14))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(210, 210, 210)
                    .addComponent(chkCarwash1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chkTyrerm1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chkseatSh1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chkAoutoDet1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chkIntDet1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chkRep1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chkWheelBal1)
                    .addContainerGap(210, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(220, Short.MAX_VALUE)
                    .addComponent(chkCarwash2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chkTyrerm2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chkseatSh2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chkAoutoDet2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chkIntDet2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chkRep2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chkWheelBal2)
                    .addGap(200, 200, 200)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(249, 249, 249)
                    .addComponent(chkCarwash3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chkTyrerm3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chkseatSh3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chkAoutoDet3)
                    .addContainerGap(249, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(262, 262, 262)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jCheckBox24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox27))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jCheckBox28)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox29)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCheckBox30)))
                    .addContainerGap(262, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Update Booking", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustIDActionPerformed

    private void chkStdDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkStdDetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkStdDetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int custId=Integer.parseInt(txtCustID.getText());
        
        
        
        String custName=txtCustName.getText();
        String vehiNum=txtVehinum.getText();
        String vehiModel=txtVehiModel.getText();
        //String dateBook=txtDateBook.getText();
        
        
        if(custName.isEmpty()){
            JOptionPane.showMessageDialog(null, "Customer name should not be empty");
        }
        if(vehiNum.isEmpty()){
            JOptionPane.showMessageDialog(null, "Vehicle number should not be empty");
        }
        if(vehiModel.isEmpty()){
            JOptionPane.showMessageDialog(null, "Vehicle model should not be empty");
        }
         if(
                ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText().isEmpty()
                )
        {
            JOptionPane.showMessageDialog(null, "Date should not be empty");
        }
         else{
         //SimpleDateFormat fomatter = new SimpleDateFormat("MM/dd/yyyy HH:mm");
        //Date dateBook = jDateChooser1.getCalendar().getTime();
        
        
         Date dateChooser=jDateChooser1.getDate();
        String date1=String.format("%1$tY-%1$tm-%1$td",dateChooser);
        
        
        String carWash,tyreRem,setshamp,autoDet,intDet,repairs,wheelbal,fullLubSer,fullDet,leathSetaCare,wheelAlign,extDet,paint,stdDet;
        
        if(chkCarwash.isSelected()){
            carWash="y";
        }
        else{
           carWash="n"; 
        }
        
        if(chkTyrerm.isSelected()){
            tyreRem="y";
        }
        else{
           tyreRem="n"; 
        }
        
        if(chkseatSh.isSelected()){
            setshamp="y";
        }
        else{
           setshamp="n"; 
        }
        
         if(chkAoutoDet.isSelected()){
            autoDet="y";
        }
        else{
           autoDet="n"; 
        }
        
         if(chkIntDet.isSelected()){
            intDet="y";
        }
        else{
           intDet="n"; 
        }
        
         if(chkRep.isSelected()){
            repairs="y";
        }
        else{
           repairs="n"; 
        }
        
        if(chkWheelBal.isSelected()){
            wheelbal="y";
        }
        else{
           wheelbal="n"; 
        }
        //////
        
        if(chkFullLub.isSelected()){
            fullLubSer="y";
            System.out.println(fullLubSer);
        }
        else{
           fullLubSer="n"; 
           System.out.println(fullLubSer);
        }
        
        if(chkFullDet.isSelected()){
            fullDet="y";
        }
        else{
           fullDet="n"; 
        }
        
        if(chkLeathCeat.isSelected()){
            leathSetaCare="y";
        }
        else{
           leathSetaCare="n"; 
        }
        
         if(chkWhelAl.isSelected()){
            wheelAlign="y";
        }
        else{
           wheelAlign="n"; 
        }
        
         if(chkExtDet.isSelected()){
            extDet="y";
        }
        else{
           extDet="n"; 
        }
        
         if(chkPaint.isSelected()){
            paint="y";
        }
        else{
           paint="n"; 
        }
        
        if(chkWheelBal.isSelected()){
            stdDet="y";
        }
        else{
           stdDet="n"; 
        }
        
        //String carWash,tyreRem,setshamp,autoDet,intDet,repairs,wheelbal,fullLubSer,fullDet,
        //leathSetaCare,wheelAlign,extDet,paint,stdDet;
        
        //validate
        
        
        
       
        try
        {
            
            //String dateBook1 = fomatter.format(dateBook);
            String sql34;
            sql34 = "Insert into bookings (custID,custName,vehicleNumber,vehicleModel,dateOfBook,carWash,tyreRemove,seatShamp,fullLubService,fullDetail,"
                    + "leatherSeatCare,autoDetail,interiorDet,repairs,wheelAlignment,extDetail,painting,wheelBalance,stdDetails)"
                    + " values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst2=con.prepareStatement(sql34);
            pst2.setInt(1,custId);
            pst2.setString(2,custName);
            pst2.setString(3,vehiNum);
            pst2.setString(4,vehiModel);
            pst2.setString(5,date1);
            
            //String carWash,tyreRem,setshamp,autoDet,intDet,repairs,wheelbal,fullLubSer,fullDet,
        //leathSetaCare,wheelAlign,extDet,paint,stdDet;
            pst2.setString(6,carWash);
            pst2.setString(7,tyreRem);
            pst2.setString(8,setshamp);
            pst2.setString(9,autoDet);
            pst2.setString(10,intDet);
            pst2.setString(11,repairs);
            pst2.setString(12,wheelbal);
            pst2.setString(13,fullLubSer);
            pst2.setString(14,fullDet);
            pst2.setString(15,leathSetaCare);
            pst2.setString(16,wheelAlign);
            pst2.setString(17,extDet);
            pst2.setString(18,paint);
            pst2.setString(19,stdDet);
                 
                        
            pst2.execute();
            
            JOptionPane.showMessageDialog(null, "Record is Successfully Added ");
            
            String sql;
            sql = "Select bookID,custID,custName,dateOfBook,vehicleNumber,vehicleModel from bookings ";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         int x=JOptionPane.showConfirmDialog(null,"Do you really want to update?");
        
        int bookID=Integer.parseInt(jLabel19.getText());
        int custID=Integer.parseInt(jTextField11.getText());
        String custName=jTextField12.getText();
        String vehiNum=jTextField9.getText();
        String vehiModel=jTextField10.getText();
        String dateBook=jTextField5.getText();
        
        String carWash,tyreRem,setshamp,autoDet,intDet,repairs,wheelbal,fullLubSer,fullDet,leathSetaCare,wheelAlign,extDet,paint,stdDet;
        
        if(jCheckBox1.isSelected()){
            carWash="y";
        }
        else{
           carWash="n"; 
        }
        
        if(jCheckBox4.isSelected()){
            tyreRem="y";
        }
        else{
           tyreRem="n"; 
        }
        
        if(jCheckBox2.isSelected()){
            setshamp="y";
        }
        else{
           setshamp="n"; 
        }
        
         if(jCheckBox6.isSelected()){
            autoDet="y";
        }
        else{
           autoDet="n"; 
        }
        
         if(jCheckBox6.isSelected()){
            intDet="y";
        }
        else{
           intDet="n"; 
        }
        
         if(jCheckBox9.isSelected()){
            repairs="y";
        }
        else{
           repairs="n"; 
        }
        
        if(jCheckBox13.isSelected()){
            wheelbal="y";
        }
        else{
           wheelbal="n"; 
        }
        //////
        
        if(jCheckBox3.isSelected()){
            fullLubSer="y";
            System.out.println(fullLubSer);
        }
        else{
           fullLubSer="n"; 
           System.out.println(fullLubSer);
        }
        
        if(jCheckBox5.isSelected()){
            fullDet="y";
        }
        else{
           fullDet="n"; 
        }
        
        if(jCheckBox7.isSelected()){
            leathSetaCare="y";
        }
        else{
           leathSetaCare="n"; 
        }
        
         if(jCheckBox10.isSelected()){
            wheelAlign="y";
        }
        else{
           wheelAlign="n"; 
        }
        
         if(jCheckBox11.isSelected()){
            extDet="y";
        }
        else{
           extDet="n"; 
        }
        
         if(jCheckBox12.isSelected()){
            paint="y";
        }
        else{
           paint="n"; 
        }
        
        if(jCheckBox14.isSelected()){
            stdDet="y";
        }
        else{
           stdDet="n"; 
        }
        
       /* int bookID=Integer.parseInt(txtBookid.getText());
        int custID=Integer.parseInt(jTextField11.getText());
        String custName=jTextField12.getText();
        String vehiNum=jTextField9.getText();
        String vehiModel=jTextField10.getText();
        String dateBook=jTextField5.getText();
        
        String carWash,tyreRem,setshamp,autoDet,intDet,repairs,wheelbal,fullLubSer,fullDet,
        leathSetaCare,wheelAlign,extDet,paint,stdDet;
        */
        
        
        //validate
        if(custName.isEmpty()){
            JOptionPane.showMessageDialog(null, "Customer name should not be empty");
        }
        if(vehiNum.isEmpty()){
            JOptionPane.showMessageDialog(null, "Vehicle number should not be empty");
        }
        if(vehiModel.isEmpty()){
            JOptionPane.showMessageDialog(null, "Vehivle model should not be empty");
        }
        if(dateBook.isEmpty()){
            JOptionPane.showMessageDialog(null, "Date should not be empty");
        }
        
        
        else{
        try{
            String s32;
             s32 = "Update bookings set custID="+custID+",custName='"+custName+"',vehicleNumber='"+vehiNum+"',vehicleModel='"+vehiModel+"',dateOfBook='"+dateBook+"',carWash='"+carWash+"',tyreRemove='"+tyreRem+"',seatShamp='"+setshamp+"',fullLubService='"+fullLubSer+"',fullDetail='"+fullDet+"',leatherSeatCare='"+leathSetaCare+"',autoDetail='"+autoDet+"',interiorDet='"+intDet+"',repairs='"+repairs+"',wheelAlignment='"+wheelAlign+"',extDetail='"+extDet+"',painting='"+paint+"',wheelBalance='"+wheelbal+"',stdDetails='"+stdDet+"' where bookID="+bookID;
            pst4=con.prepareStatement(s32);
            //pst4.execute();
            pst4.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Record is Successfully Updated ");
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        updateTableLoad();
        
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       // String dateOfBook=txtDateBook.getText();
        
       // SimpleDateFormat fomatter = new SimpleDateFormat("MM/dd/yyyy ");
        //Date dateOfBook = jDateChooser1.getCalendar().getTime();
      //  String dBook=dateOfBook.toString();
        
         if(
                ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText().isEmpty()
                )
        {
            JOptionPane.showMessageDialog(null, "Date should not be empty");
        }
        
         else{
        Date dateChooser=jDateChooser1.getDate();
        String date1=String.format("%1$tY-%1$tm-%1$td",dateChooser);
        
        try{
            //String dateOfBook1 = fomatter.format(dateOfBook);
            String sql;
            sql = "Select bookID,custID,custName,dateOfBook,vehicleNumber,vehicleModel from bookings where dateOfBook='"+date1+"' ";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            
        }
         }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int raw=jTable2.getSelectedRow();
        
        String bookId=jTable2.getValueAt(raw,0).toString();
        String cusID=jTable2.getValueAt(raw,1).toString();
        String custName=jTable2.getValueAt(raw,2).toString();
        String vehiNum=jTable2.getValueAt(raw,3).toString();
        String vehimodel=jTable2.getValueAt(raw,4).toString();
        String date=jTable2.getValueAt(raw,5).toString();
        
        String carWash=jTable2.getValueAt(raw,6).toString();
        String tyreRem=jTable2.getValueAt(raw,7).toString();
        String setshamp=jTable2.getValueAt(raw,8).toString();
        String autoDet=jTable2.getValueAt(raw,9).toString();
        String intDet=jTable2.getValueAt(raw,10).toString();
        String repairs=jTable2.getValueAt(raw,11).toString();
        String wheelbal=jTable2.getValueAt(raw,12).toString();
        String fullLubSer=jTable2.getValueAt(raw,13).toString();
        String fullDet=jTable2.getValueAt(raw,14).toString();
        String leathSetaCare=jTable2.getValueAt(raw,15).toString();
        String wheelAlign=jTable2.getValueAt(raw,16).toString();
        String extDet=jTable2.getValueAt(raw,17).toString();
        String paint=jTable2.getValueAt(raw,18).toString();
        String stdDet=jTable2.getValueAt(raw,19).toString();
        
        jLabel19.setText(bookId);
        jTextField11.setText(cusID);
        jTextField12.setText(custName);
        jTextField9.setText(vehiNum);
        jTextField10.setText(vehimodel);
        jTextField5.setText(date);
        
        
        if("y".equals(carWash)){
        jCheckBox1.setSelected(true);
        }
        if("y".equals(tyreRem)){
        jCheckBox4.setSelected(true);
        }
        if("y".equals(setshamp)){
        jCheckBox2.setSelected(true);
        }
        if("y".equals(autoDet)){
        jCheckBox6.setSelected(true);
        }
        if("y".equals(intDet)){
        jCheckBox8.setSelected(true);
        }
        if("y".equals(repairs)){
        jCheckBox9.setSelected(true);
        }
        if("y".equals(wheelbal)){
        jCheckBox13.setSelected(true);
        }
        if("y".equals(fullLubSer)){
        jCheckBox3.setSelected(true);
        }
        if("y".equals(fullDet)){
        jCheckBox5.setSelected(true);
        }
        if("y".equals(leathSetaCare)){
        jCheckBox7.setSelected(true);
        }
        if("y".equals(wheelAlign)){
        jCheckBox10.setSelected(true);
        }
        if("y".equals(extDet)){
        jCheckBox11.setSelected(true);
        }
        if("y".equals(paint)){
        jCheckBox12.setSelected(true);
        }
        if("y".equals(stdDet)){
        jCheckBox14.setSelected(true);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        int bookId=Integer.parseInt(jLabel19.getText());
        
        try
            {
            String sql1;
            sql1 = "DELETE  FROM bookings WHERE bookID="+bookId+"";
            pst1=con.prepareStatement(sql1);
            pst1.execute();
            
            JOptionPane.showMessageDialog(null, "Record is Successfully Deleted ");
            }
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtCustNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCustNameMouseClicked
        // TODO add your handling code here:
        
        String Custname=txtCustName.getText();
        
        try{
            String sr="select custID from generalcustomer where custName='"+Custname+"'";
            pst1=con.prepareStatement(sr);
           rs =pst1.executeQuery();
           rs.next();
           int custId = rs.getInt("custID");
           String cust_Id=String.valueOf(custId);
           
           txtCustID.setText(cust_Id);
           
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Unregistered General Customer");
        }
    }//GEN-LAST:event_txtCustNameMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        txtVehinum.setText(null);
        txtVehiModel.setText(null);
        
        chkCarwash.setSelected(false);
        chkTyrerm.setSelected(false);
        chkseatSh.setSelected(false);
        chkAoutoDet.setSelected(false);
        chkIntDet.setSelected(false);
        chkRep.setSelected(false);
        chkWheelBal.setSelected(false);
        chkFullLub.setSelected(false);
        chkFullDet.setSelected(false);
        chkLeathCeat.setSelected(false);
        chkWhelAl.setSelected(false);
        chkExtDet.setSelected(false);
        chkPaint.setSelected(false);
        chkStdDet.setSelected(false);
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCustNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCustNameMouseEntered
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtCustNameMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustomerName;
    private javax.swing.JCheckBox chkAoutoDet;
    private javax.swing.JCheckBox chkAoutoDet1;
    private javax.swing.JCheckBox chkAoutoDet2;
    private javax.swing.JCheckBox chkAoutoDet3;
    private javax.swing.JCheckBox chkCarwash;
    private javax.swing.JCheckBox chkCarwash1;
    private javax.swing.JCheckBox chkCarwash2;
    private javax.swing.JCheckBox chkCarwash3;
    private javax.swing.JCheckBox chkExtDet;
    private javax.swing.JCheckBox chkFullDet;
    private javax.swing.JCheckBox chkFullLub;
    private javax.swing.JCheckBox chkIntDet;
    private javax.swing.JCheckBox chkIntDet1;
    private javax.swing.JCheckBox chkIntDet2;
    private javax.swing.JCheckBox chkLeathCeat;
    private javax.swing.JCheckBox chkPaint;
    private javax.swing.JCheckBox chkRep;
    private javax.swing.JCheckBox chkRep1;
    private javax.swing.JCheckBox chkRep2;
    private javax.swing.JCheckBox chkStdDet;
    private javax.swing.JCheckBox chkTyrerm;
    private javax.swing.JCheckBox chkTyrerm1;
    private javax.swing.JCheckBox chkTyrerm2;
    private javax.swing.JCheckBox chkTyrerm3;
    private javax.swing.JCheckBox chkWheelBal;
    private javax.swing.JCheckBox chkWheelBal1;
    private javax.swing.JCheckBox chkWheelBal2;
    private javax.swing.JCheckBox chkWhelAl;
    private javax.swing.JCheckBox chkseatSh;
    private javax.swing.JCheckBox chkseatSh1;
    private javax.swing.JCheckBox chkseatSh2;
    private javax.swing.JCheckBox chkseatSh3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtCustID;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtVehiModel;
    private javax.swing.JTextField txtVehinum;
    // End of variables declaration//GEN-END:variables
}
