/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacePackage;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import mycode.DBconnect;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HP
 */
public class LoanDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form LoanDetails
     */
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs=null;
   
    public LoanDetails() {
        initComponents();
         conn=DBconnect.connect();
        fillCombo();
        tableload();
    }
    
    public void fillCombo(){
   String a ="APPROVED";
   String sql="select loanId from loan where Status='"+a+"'";
   
   try
   {
       pst=conn.prepareStatement(sql);
       rs=pst.executeQuery();
       while(rs.next())
       {
           cmbloanid.addItem(rs.getString("loanId"));
       }
   }
   
   catch(Exception e){
   System.out.println(e);
   }
   }

    public void tableload()
    {
       try {
           
           String sql1 = "SELECT Loan_ID,Employee_ID,Amount,Time_Duration,Installment,Remaining_Installments,Amount_Paid FROM loandetails";
            pst = conn.prepareStatement(sql1);
            rs = pst.executeQuery();
            
            
            tblloanDetails.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            
         
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public void clear_update()
   {
       txtn_ins.setText("");
       tableload();
       
   }
   
   public void clear()
   {
        
        txteid.setText("");
        txtamount.setText("");
        txtinstallment.setText("");
        
        tableload();
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbloanid = new javax.swing.JComboBox();
        txteid = new javax.swing.JTextField();
        txtamount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbtime = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtinstallment = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblloanDetails = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtn_ins = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1017, 609));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Loan Details");

        jLabel2.setText("Loan ID");

        jLabel3.setText("Employee ID");

        jLabel4.setText("Amount");

        cmbloanid.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbloanidPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbloanid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbloanidMouseClicked(evt);
            }
        });
        cmbloanid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbloanidActionPerformed(evt);
            }
        });

        txteid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(43, 43, 43)
                        .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txteid, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbloanid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbloanid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txteid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtamount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel5.setText("Time Duration ( Months )");

        cmbtime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "6", "12" }));
        cmbtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtimeActionPerformed(evt);
            }
        });

        jLabel6.setText("Installment");

        txtinstallment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinstallmentActionPerformed(evt);
            }
        });

        jButton1.setText("Calculate Installment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblloanDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tblloanDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblloanDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblloanDetails);

        jLabel8.setText("Number of Installments");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Add Payment");

        jButton2.setText("Add Payment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6)
                            .addComponent(jLabel8))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtn_ins, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jButton2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtn_ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton6))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(167, 167, 167)
                                .addComponent(jButton5)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cmbtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE))
                                    .addComponent(txtinstallment)))
                            .addComponent(jButton4)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(92, 92, 92)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(cmbtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtinstallment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jButton1))))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbloanidPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbloanidPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String temp= (String) cmbloanid.getSelectedItem();

       
            String sql ="select * from loan where loanId=?";

            try
            {
                pst=conn.prepareStatement(sql);
                pst.setString(1, temp);
                rs=pst.executeQuery();

                if(rs.next())
                {
                    String add1=rs.getString("EmpID")+"_EMP";
                    txteid.setText(add1);
                    String add2=rs.getString("Amount");
                    txtamount.setText(add2);
                }

            }
            catch(Exception e)
            {
                System.out.println();
            }

        
        
        
     /*   txtbsal.setText("");
        txthra.setText("");
        txtlta.setText("");
        txtcea.setText("");
        txtda.setText("");
        tableload();
*/
    }//GEN-LAST:event_cmbloanidPopupMenuWillBecomeInvisible

    private void cmbloanidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbloanidMouseClicked
        // TODO add your handling code here:
        /* try
        {
            String q="select Name from employee where username=?";
            pst=conn.prepareStatement(q);
            pst.setString(1, (String)cmbempid.getSelectedItem());
            rs =pst.executeQuery();

            txtname.setText(rs.getString("Name"));
        }

        catch(Exception e)
        {
            System.out.println(e);
        }*/

    }//GEN-LAST:event_cmbloanidMouseClicked

    private void cmbloanidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbloanidActionPerformed

    }//GEN-LAST:event_cmbloanidActionPerformed

    private void txteidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteidActionPerformed

    private void cmbtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtimeActionPerformed

    private void txtinstallmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinstallmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinstallmentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String time = cmbtime.getSelectedItem().toString();
        String amt = txtamount.getText();
        
        double amount = Double.parseDouble(amt);
        int tym = Integer.parseInt(time);
        
        double am = amount/tym;
        double t = new BigDecimal(am).setScale(2, RoundingMode.HALF_UP).doubleValue();
        String ins = Double.toString(t);
        
        txtinstallment.setText(ins);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String loanid =cmbloanid.getSelectedItem().toString();
        String eid=txteid.getText();
        String amt=txtamount.getText();
        String tym =cmbtime.getSelectedItem().toString();
        String ins=txtinstallment.getText();
        String s1=tym;
        String s2="0";
        try{
            
        String t="select * from loandetails where Loan_ID='"+loanid+"'";  
        pst=conn.prepareStatement(t);
        rs =pst.executeQuery();
        if(rs.next())
        {
            JOptionPane.showMessageDialog(null, "Loan ID already Exists.");
        }
                 
        
        else{
            String y="INSERT INTO loandetails (Loan_ID,Employee_ID,Amount,Time_Duration,Installment,Remaining_Installments,Amount_Paid) VALUES ('"+loanid+"','"+eid+"','"+amt+"','"+tym+"','"+ins+"','"+s1+"','"+s2+"')";
        pst=conn.prepareStatement(y);
        pst.execute();
        tableload();
        JOptionPane.showMessageDialog(null, "Record Successfully Added");
        }
        
       
        
           
       
        
        }
        
        catch(Exception e){
        
            System.out.println(e);
        }
        
        
        
        
   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int s1= JOptionPane.showConfirmDialog(null, "do you want to delete");
        
        if( s1==0)
        {
            String lnid = cmbloanid.getSelectedItem().toString();
            
            try {
                
                String q1 = "DELETE FROM loandetails WHERE Loan_ID = '"+lnid+"'";
                pst = conn.prepareStatement(q1);
                pst.execute();
                tableload();
               
                
               // tableload1();
                
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          int s1= JOptionPane.showConfirmDialog(null, "do you want to Update ?");
         
        if( s1==0){
            
        
        String c=null;
        String d=null ;
        String lnid = cmbloanid.getSelectedItem().toString();
        String n_ins = txtn_ins.getText();
        String ins = txtinstallment.getText();
       
        
        if("".equals(n_ins)||"".equals(lnid)||"".equals(ins))
        {
            JOptionPane.showMessageDialog(null, "Fields are having null values cannot add payment.");
        }
        
        
        
        
        else{
         int a = Integer.parseInt(n_ins);
        Double b = Double.parseDouble(ins);
          try{  
            String sql="select Remaining_Installments,Amount_Paid from loandetails where Loan_ID='"+lnid+"'";
   
   
       pst=conn.prepareStatement(sql);
       rs=pst.executeQuery();
       while(rs.next())
       {
           c =rs.getString("Remaining_Installments");
           d =rs.getString("Amount_Paid");
       }
   
        int e = Integer.parseInt(c);
        Double f = Double.parseDouble(d);
        
        int g=e - a;
        double h=f+(a*b);
        
        double t = new BigDecimal(h).setScale(2, RoundingMode.HALF_UP).doubleValue();
        
        String i = Integer.toString(g);
        String j = Double.toString(t);
       
    String q="update loandetails set Remaining_Installments='"+i+"',Amount_Paid='"+j+"'where Loan_ID='"+lnid+"'";
               pst=conn.prepareStatement(q);
               pst.executeUpdate();
               tableload();
  
   }
            
            
              
            
           
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter numbers only");
        }
        }
          
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        clear_update();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tblloanDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblloanDetailsMouseClicked
        // TODO add your handling code here:
        
         int row = tblloanDetails.getSelectedRow();
        
        
        String lnid = tblloanDetails.getValueAt(row, 0).toString();
        String eid = tblloanDetails.getValueAt(row, 1).toString();
        String amt = tblloanDetails.getValueAt(row, 2).toString();
        String tym = tblloanDetails.getValueAt(row, 3).toString();
        String ins = tblloanDetails.getValueAt(row, 4).toString();
       
        
        
        cmbloanid.setSelectedItem(lnid);
        txteid.setText(eid);
        txtamount.setText(amt);
        cmbtime.setSelectedItem(tym);
        txtinstallment.setText(ins);
        
        
    }//GEN-LAST:event_tblloanDetailsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbloanid;
    private javax.swing.JComboBox cmbtime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblloanDetails;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txteid;
    private javax.swing.JTextField txtinstallment;
    private javax.swing.JTextField txtn_ins;
    // End of variables declaration//GEN-END:variables
}
