/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacePackage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import mycode.DBconnect;
import net.proteanit.sql.DbUtils;




/**
 *
 * @author Sanjani
 */
public class SalaryDetails extends javax.swing.JInternalFrame {
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs=null;
   

    /**
     * Creates new form SalaryDetails
     */
    public SalaryDetails() {
        initComponents();
        
        //connect to db
        
        conn=DBconnect.connect();
        fillCombo();
        fillCombo1();
        fillCombo2();
        tableload();
       
    }
    
    
    public void tableload()
    {
       try {
           
           String sql1 = "SELECT Employee_ID ,Name,Basic_Salary ,HRA ,LTA ,CEA ,DA ,Salary_Scheme FROM empsaldetails";
            pst = conn.prepareStatement(sql1);
            rs = pst.executeQuery();
            
            
            tblSalDetails.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            
         
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
  public void fillCombo(){
   
   String sql="select username from employee ";
   
   try
   {
       pst=conn.prepareStatement(sql);
       rs=pst.executeQuery();
       while(rs.next())
       {
           cmbempid.addItem(rs.getString("username"));
       }
   }
   
   catch(Exception e){
   System.out.println(e);
   }
   }
  
  public void fillCombo1(){
   
   String sql="select username from manager ";
   
   try
   {
       pst=conn.prepareStatement(sql);
       rs=pst.executeQuery();
       while(rs.next())
       {
           cmbempid.addItem(rs.getString("username"));
       }
   }
   
   catch(Exception e){
   System.out.println(e);
   }
   }
  
  public void fillCombo2(){
   
   String sql="select Category from categorydetails ";
   
   try
   {
       pst=conn.prepareStatement(sql);
       rs=pst.executeQuery();
       while(rs.next())
       {
           cmbsalscheme.addItem(rs.getString("Category"));
       }
   }
   
   catch(Exception e){
   System.out.println(e);
   }
   }
   
   public void clear_search()
   {
       txtEmployeeID.setText("");
       tableload();
       
   }
   
   public void clear()
   {
        
        txtname.setText("");
        txtbsal.setText("");
        txthra.setText("");
        txtlta.setText("");
        txtcea.setText("");
        txtda.setText("");
        tableload();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblBasicSal = new javax.swing.JLabel();
        txthra = new javax.swing.JTextField();
        txtbsal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalDetails = new javax.swing.JTable();
        btnAddemp = new javax.swing.JButton();
        btnUpdateEmp = new javax.swing.JButton();
        btnDeleteEmp = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblEmployeeID = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcea = new javax.swing.JTextField();
        txtda = new javax.swing.JTextField();
        txtlta = new javax.swing.JTextField();
        lblEmpID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        cmbempid = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbsalscheme = new javax.swing.JComboBox();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(1030, 630));
        setMinimumSize(new java.awt.Dimension(1030, 630));
        setPreferredSize(new java.awt.Dimension(1017, 609));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1017, 630));

        lblBasicSal.setText("Basic Salary");

        tblSalDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Salary ID", "Employee ID ", "Name", "Basic Salary", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tblSalDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSalDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSalDetails);

        btnAddemp.setText("Add");
        btnAddemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddempActionPerformed(evt);
            }
        });

        btnUpdateEmp.setText("Update");
        btnUpdateEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEmpActionPerformed(evt);
            }
        });

        btnDeleteEmp.setText("Delete");
        btnDeleteEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmpActionPerformed(evt);
            }
        });

        lblEmployeeID.setText("Employee ID");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnRefresh.setText("Clear");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblEmployeeID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmployeeID))
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh)
                .addGap(21, 21, 21))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Employee Wise Salary Details");

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Children’s Education Allowance");

        jLabel5.setText("Leave Travel Assistance");

        jLabel6.setText("House Rent Allowance");

        jLabel7.setText("Dearness Allowance");

        txtcea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtceaActionPerformed(evt);
            }
        });

        txtda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdaActionPerformed(evt);
            }
        });

        lblEmpID.setText("Employee ID");

        lblName.setText("Name");

        cmbempid.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbempidPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbempid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbempidMouseClicked(evt);
            }
        });
        cmbempid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbempidActionPerformed(evt);
            }
        });

        jLabel2.setEnabled(false);

        jLabel4.setEnabled(false);

        jLabel8.setText("Salary Scheme");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(799, 801, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAddemp)
                                        .addGap(102, 102, 102)
                                        .addComponent(btnUpdateEmp)
                                        .addGap(137, 137, 137)
                                        .addComponent(btnDeleteEmp)
                                        .addGap(98, 98, 98)
                                        .addComponent(jButton1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEmpID)
                                            .addComponent(lblName)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblBasicSal)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbempid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtbsal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txthra, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel7)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtlta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel8))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cmbsalscheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtda, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtcea, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addGap(44, 44, 44))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cmbempid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblEmpID))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblName)
                                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtbsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblBasicSal)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(txtlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(txtcea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(txtda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txthra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(cmbsalscheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddemp)
                            .addComponent(btnUpdateEmp)
                            .addComponent(btnDeleteEmp)
                            .addComponent(jButton1))
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel2)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(367, 445, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddempActionPerformed
        // TODO add your handling code here:
       
        
        
        
        
        
        
        String employeeID = cmbempid.getSelectedItem().toString();
        String name =txtname.getText();
        String basicSalary = txtbsal.getText();
        String hra = txthra.getText();
        String lta =txtlta.getText();
        String da = txtda.getText();
        String cea =txtcea.getText();
        String cat = cmbsalscheme.getSelectedItem().toString();
        
        
        if("".equals(employeeID)||"".equals(basicSalary)||"".equals(hra)||"".equals(lta)||"".equals(da)||"".equals(cea))
        {
            JOptionPane.showMessageDialog(null, "Fields cannot have null values");
        }
        
        try{
            
        String t="select * from empsaldetails where Employee_ID='"+employeeID+"'";  
        pst=conn.prepareStatement(t);
        rs =pst.executeQuery();
        if(rs.next())
        {
            JOptionPane.showMessageDialog(null, "Employee ID already Exists.");
        }
                 
        
            
        
        
        
        
        
        else{
            String y="INSERT INTO empsaldetails (Employee_ID,Name,Basic_Salary,HRA,LTA,CEA,DA,Salary_Scheme) VALUES ('"+employeeID+"','"+name+"','"+basicSalary+"','"+hra+"','"+lta+"','"+cea+"','"+da+"','"+cat+"')";
        pst=conn.prepareStatement(y);
        pst.execute();
        
        tableload();
        JOptionPane.showMessageDialog(null, "Record Successfully Added");
        }
        
       
        
           
       
        
        }
        
        catch(Exception e){
        
             JOptionPane.showMessageDialog(null, "Please enter numbers only");
        }
        
    }//GEN-LAST:event_btnAddempActionPerformed

    private void cmbempidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbempidActionPerformed
       
        
       
    }//GEN-LAST:event_cmbempidActionPerformed

    private void btnDeleteEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmpActionPerformed
        // TODO add your handling code here:
          int s1= JOptionPane.showConfirmDialog(null, "do you want to delete");
        
        if( s1==0)
        {
            String empid = cmbempid.getSelectedItem().toString();
            
            try {
                
                String q1 = "DELETE FROM empsaldetails WHERE Employee_ID = '"+empid+"'";
                pst = conn.prepareStatement(q1);
                pst.execute();
                tableload();
               
                
               // tableload1();
                
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        
        
    }//GEN-LAST:event_btnDeleteEmpActionPerformed

    private void btnUpdateEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEmpActionPerformed
      // TODO add your handling code here: 
    
         int s1= JOptionPane.showConfirmDialog(null, "do you want to Update ?");
         
        if( s1==0){
            
        
        
        String eid = cmbempid.getSelectedItem().toString();
        String name = txtname.getText();
        String basicSal = txtbsal.getText();
        String hra = txthra.getText();
        String lta =txtlta.getText();
        String da = txtda.getText();
        String cea =txtcea.getText();
        String cat=cmbsalscheme.getSelectedItem().toString();
        
        try{
               String b="update empsaldetails set Basic_Salary='"+basicSal+"',HRA='"+hra+"',LTA='"+lta+"',CEA='"+cea+"',DA='"+da+"', Salary_Scheme='"+cat+"'where Employee_ID='"+eid+"'";
               pst=conn.prepareStatement(b);
               pst.executeUpdate();
               tableload();
            
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter numbers only");
        }
        }
        
       
        
        
    }//GEN-LAST:event_btnUpdateEmpActionPerformed

    private void tblSalDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSalDetailsMouseClicked
        // TODO add your handling code here:
        int row = tblSalDetails.getSelectedRow();
        
        
        String eid = tblSalDetails.getValueAt(row, 0).toString();
        String name = tblSalDetails.getValueAt(row, 1).toString();
        String bSal = tblSalDetails.getValueAt(row, 2).toString();
        String hra = tblSalDetails.getValueAt(row, 3).toString();
        String lta = tblSalDetails.getValueAt(row, 4).toString();
        String cea = tblSalDetails.getValueAt(row, 5).toString();
        String da = tblSalDetails.getValueAt(row, 6).toString();
        
        
        
        cmbempid.setSelectedItem(eid);
        txtname.setText(name);
        txtbsal.setText(bSal);
        txthra.setText(hra);
        txtlta.setText(lta);
        txtcea.setText(cea);
        txtda.setText(da);
        
        
        
    }//GEN-LAST:event_tblSalDetailsMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String eid = txtEmployeeID.getText();
        
        try{
            String b="Select Employee_ID,Name,Basic_Salary,HRA,LTA,CEA,DA,Salary_Scheme from empsaldetails WHERE Employee_ID LIKE '%"+eid+"%'";
        pst=conn.prepareStatement(b);
        rs = pst.executeQuery();
            
            
            tblSalDetails.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception  e){
            
        System.out.println(e);
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        
         clear_search();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clear();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtceaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtceaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtceaActionPerformed

    private void txtdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdaActionPerformed

    private void cmbempidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbempidMouseClicked
        // TODO add your handling code here:
       /* try
       {
           String q="select Name from employee where username=?";
           pst=conn.prepareStatement(q);
           pst.setString(1, (String)cmbempid.getSelectedItem());
           rs =pst.executeQuery();
        
           txtname.setText(rs.getString("Name"));
       }
       
       catch(Exception e)
       {
           System.out.println(e);
       }*/
        
    }//GEN-LAST:event_cmbempidMouseClicked

    private void cmbempidPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbempidPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
            String temp= (String) cmbempid.getSelectedItem();
            
            if(temp.endsWith("EMP")){
                 String sql ="select Name from employee where username=?";
        
        try
        {
            pst=conn.prepareStatement(sql);
            pst.setString(1, temp);
            rs=pst.executeQuery();
            
            if(rs.next())
            {
                String add1=rs.getString("Name");
                txtname.setText(add1);
            }
            
        }
        catch(Exception e)
        {
        System.out.println();
        }
        
        
        }
        else
        {
            String sql ="select Name from manager where username=?";
        
        try
        {
            pst=conn.prepareStatement(sql);
            pst.setString(1, temp);
            rs=pst.executeQuery();
            
            if(rs.next())
            {
                String add1=rs.getString("Name");
                txtname.setText(add1);
            }
            
        }
        catch(Exception e)
        {
        System.out.println();
        }
        
        }
        txtbsal.setText("");
        txthra.setText("");
        txtlta.setText("");
        txtcea.setText("");
        txtda.setText("");
        tableload();
           
    }//GEN-LAST:event_cmbempidPopupMenuWillBecomeInvisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddemp;
    private javax.swing.JButton btnDeleteEmp;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdateEmp;
    private javax.swing.JComboBox cmbempid;
    private javax.swing.JComboBox cmbsalscheme;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBasicSal;
    private javax.swing.JLabel lblEmpID;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tblSalDetails;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtbsal;
    private javax.swing.JTextField txtcea;
    private javax.swing.JTextField txtda;
    private javax.swing.JTextField txthra;
    private javax.swing.JTextField txtlta;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
