/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itp;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import mycode.DBconnect;
import net.proteanit.sql.DbUtils;
import java.util.regex.Matcher;
import java.util.regex.Pattern;



/**
 *
 * @author Dissanayaka
 */
public class supplier extends javax.swing.JInternalFrame {
    Connection conn       = null;
    PreparedStatement pst = null;
    ResultSet   rs = null;

    /**
     * Creates new form supplier
     */
    public supplier() {
        initComponents();
        conn = DBconnect.connect();
        
       tableload();
       
    }
    
    private void tableload(){
        
        try{
        String sql = " SELECT Name,ID,Country,Addrs,Email,Contact1,Contact2,Fax,Ccode  From supplier ";
       pst = conn.prepareStatement(sql);
       rs = (ResultSet) pst.executeQuery();
       
       suptable.setModel(DbUtils.resultSetToTableModel((ResultSet) rs));
        
                
                }catch(Exception e){
                     System.out.println(e.getMessage());
                }
        
        
    }
    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        adrsbox = new javax.swing.JTextField();
        eidbox = new javax.swing.JTextField();
        n1box = new javax.swing.JTextField();
        n2box = new javax.swing.JTextField();
        faxbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        namebox = new javax.swing.JComboBox();
        countrybox = new javax.swing.JComboBox();
        ccbox = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        suptable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        idbox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1030, 630));

        jPanel11.setBackground(new java.awt.Color(0, 153, 153));
        jPanel11.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel18.setBackground(new java.awt.Color(0, 153, 153));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(" Manage Suppliers");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1030, 550));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Company Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Company ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Country");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Company Address");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Email ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Contact Dealer 1");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Contact Dealer 2");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText(" Fax NO");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Country code");

        adrsbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adrsbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adrsboxKeyTyped(evt);
            }
        });

        eidbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        eidbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                eidboxKeyTyped(evt);
            }
        });

        n1box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        n1box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n1boxMouseClicked(evt);
            }
        });
        n1box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1boxActionPerformed(evt);
            }
        });
        n1box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                n1boxKeyTyped(evt);
            }
        });

        n2box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        n2box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                n2boxKeyTyped(evt);
            }
        });

        faxbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        faxbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faxboxActionPerformed(evt);
            }
        });
        faxbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                faxboxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                faxboxKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Supplier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        namebox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        namebox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MAZDA", "HONDA", "TOYOTA", "NISSAN", "ISUZU", "GEELY", "JAC" }));

        countrybox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        countrybox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Japan", "India", "China", "Germany", "South Korea" }));

        ccbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ccbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+78", "+965", "+898", "+66" }));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update Supplier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        suptable.setBackground(new java.awt.Color(204, 204, 255));
        suptable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        suptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        suptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suptableMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suptableMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(suptable);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Delete Supplier");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        idbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "1001", "2002", "3003", "4004", "5005", "6006", "7007", "8008", "9009", "100010", "110011", "120012", "130013", "140014", "150015", "160016", "170017", "180018" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(28, 28, 28))))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eidbox)
                    .addComponent(adrsbox)
                    .addComponent(countrybox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namebox, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton4)
                        .addGap(46, 46, 46)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ccbox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(n2box, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(n1box, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(faxbox, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(109, 109, 109))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(idbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(countrybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(adrsbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(n1box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(n2box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(ccbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addComponent(faxbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton4))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(eidbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 91, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Suppliers", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 boolean var1=false;
  boolean var2=false;
 
 
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           
  int x =JOptionPane.showConfirmDialog(null, "Do you really want to add ?");
        if(x==0)
        {
        
        String namebox1 = namebox.getSelectedItem().toString();
       // int idbox1 =  Integer.parseInt((String)idbox.getSelectedItem());
        int idbox1 =0;
        
        
        String countrybox1  = countrybox.getSelectedItem().toString();
        String adrsbox1    = adrsbox.getText();
        String eidbox1    = eidbox.getText();
       // int n1box1    = Integer.parseInt((String)n1box .getText());
        int n1box1  =0;        
        int n2box1  =0;
               
        
        //int n2box1    = Integer.parseInt((String)n2box .getText());
        int faxbox1=0;        
        //int faxbox1    = Integer.parseInt((String)faxbox .getText());
       // int ccodebox1 = Integer.parseInt((String)ccbox.getSelectedItem());
        int ccodebox1 =0;
        
        
//        
//         if(!n1box1.matches("\\d{10}") 
//{ 
//    jLabel9.setText("Enter your valid mobile Number"); } 
//        
//  

               
        
 if(namebox1.length()!=0 && countrybox1.length()!=0 && adrsbox1 .length()!=0 &&  eidbox1.length()!=0)
{
		var1 = true;

//else 
//{
//	JOptionPane.showMessageDialog(null, "You haven't fill all the details. Please fill All!!!!");
//}
        
      
 if(eidbox1.matches("[a-zA-Z0-9\\.]+@[a-zA-Z0-9\\-\\_\\.]+\\.[a-zA-Z0-9]{3}"))
         {
             var2 = true;
//             
//                idbox1 =  Integer.parseInt((String)idbox.getSelectedItem());
//              n1box1    = Integer.parseInt((String)n1box .getText());
//        n2box1    = Integer.parseInt((String)n2box .getText());
//         faxbox1    = Integer.parseInt((String)faxbox .getText());
//         ccodebox1 = Integer.parseInt((String)ccbox.getSelectedItem());
//        
         }
else
 {
     JOptionPane.showMessageDialog(null, "incorrect email address!!!!");
     
 }
 
 
 
                idbox1 =  Integer.parseInt((String)idbox.getSelectedItem());
              n1box1    = Integer.parseInt((String)n1box .getText());
        n2box1    = Integer.parseInt((String)n2box .getText());
        
         faxbox1    = Integer.parseInt((String)faxbox .getText());
         ccodebox1 = Integer.parseInt((String)ccbox.getSelectedItem());
        
}   
 else 
{
	JOptionPane.showMessageDialog(null, "You haven't fill all the details. Please fill All!!!!");
}
 
 
 
 

 
 if(var1 == true && var2 == true )
           {
               
               
   
        
        try{
            String j = "INSERT INTO supplier (Name,ID,Country,Addrs,Email,Contact1,Contact2,Fax,Ccode) values" + " ('"+namebox1+"',"+idbox1+",'"+countrybox1+"','"+adrsbox1+"', '"+eidbox1+"',"+n1box1+","+n2box1+","+faxbox1+","+ccodebox1+")";
            pst = conn.prepareStatement(j);
            pst.execute();
            
           tableload();
        } 
        catch(Exception e){
            
        }
        JOptionPane.showMessageDialog(null, "Record successfuly added");
               
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
       jPanel2.removeAll();
       deletesupplier s1 =new deletesupplier();
       jPanel2 .add(s1).setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void suptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suptableMouseClicked
       
        int r = suptable.getSelectedRow();
        
        String idbox1      = suptable.getValueAt(r, 1).toString();
        String namebox1    = suptable.getValueAt(r, 0).toString();
        String countrybox1 = suptable.getValueAt(r, 2).toString();
        String adrsbox1    = suptable.getValueAt(r, 3).toString();
        String eidbox1     = suptable.getValueAt(r, 4).toString();
        String n1box1      = suptable.getValueAt(r, 5).toString();
        String n2box1      = suptable.getValueAt(r, 6).toString();
        String faxbox1     = suptable.getValueAt(r, 7).toString();
        String ccodebox1   = suptable.getValueAt(r, 8).toString();
       
         
         idbox.setSelectedItem(idbox1);
         namebox.setSelectedItem(namebox1);
         countrybox.setSelectedItem(countrybox1);
         adrsbox.setText(adrsbox1);
         eidbox.setText(eidbox1);
         n1box.setText(n1box1);
         n2box.setText(n2box1);
         faxbox.setText(faxbox1);
         ccbox.setSelectedItem(ccodebox1);
        
    }//GEN-LAST:event_suptableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           int x =JOptionPane.showConfirmDialog(null, "Do you really want to update ?");
        
        if(x==0)
        {
        int idbox1 =  Integer.parseInt((String)idbox.getSelectedItem());
        String namebox1 = namebox.getSelectedItem().toString();
        String countrybox1  = countrybox.getSelectedItem().toString();
        String adrsbox1    = adrsbox.getText();
        String eidbox1    = eidbox.getText();
        int n1box1    = Integer.parseInt((String)n1box .getText());
        int n2box1    = Integer.parseInt((String)n2box .getText());
        int faxbox1    = Integer.parseInt((String)faxbox .getText());
        int ccodebox1 = Integer.parseInt((String)ccbox.getSelectedItem());
        
       
                
              String j;
               j = "UPDATE supplier SET Name='"+namebox1+"',Country='"+ countrybox1+"',Addrs='"+adrsbox1+"',Email='"+eidbox1+"',Contact1="+n1box1+",Contact2="+n2box1+",Fax="+faxbox1+", Ccode="+ccodebox1+"  WHERE ID='"+idbox1+"'";
               try{
               pst=conn.prepareStatement(j);
               pst.executeUpdate();
               tableload();
               
               JOptionPane.showMessageDialog(null, "Record successfuly Updated");
               }
               catch(SQLException | HeadlessException e){
               
               
    }  
        
        }  
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void n1boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n1boxKeyTyped
        // TODO add your handling code here:
              char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE) ){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_n1boxKeyTyped

    private void n2boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n2boxKeyTyped
        // TODO add your handling code here:
              char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE) ){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_n2boxKeyTyped

    private void faxboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_faxboxKeyTyped
        // TODO add your handling code here:
              char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE) ){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_faxboxKeyTyped

    private void faxboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_faxboxKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_faxboxKeyReleased

    private void faxboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faxboxActionPerformed
        // TODO add your handling code here:
        String num=faxbox.getText();
        try {
            Integer.parseInt(num);
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(null, "Enter numbers Only", "ERROR", JOptionPane.ERROR_MESSAGE);
            faxbox.setText("");
        }
    }//GEN-LAST:event_faxboxActionPerformed

    private void n1boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1boxActionPerformed

    private void adrsboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adrsboxKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(c=='a'||c=='b'||c=='c'||c=='d'||c=='e'||c=='f'||c=='g'||c=='h'||c=='i'||c=='j'||c=='k'||c=='l'||c=='m'||c=='n'||c=='o'||c=='p'||c=='q'||c=='r'||c=='s'||c=='t'||c=='u'||c=='v'||c=='w'||c=='x'||c=='y'||c=='z'||c=='A'||c=='B'||c=='C'||c=='D'||c=='E'||c=='F'||c=='G'||c=='H'||c=='I'||c=='J'||c=='K'||c=='L'||c=='M'||c=='N'||c=='O'||c=='P'||c=='Q'||c=='R'||c=='S'||c=='T'||c=='U'||c=='V'||c=='W'||c=='X'||c=='Y'||c=='Z'||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE||c==KeyEvent.VK_SPACE||c==KeyEvent.VK_BACK_SPACE))
                {
                    evt.consume();
                    JOptionPane.showMessageDialog(this,"Only letters please");
                }
    }//GEN-LAST:event_adrsboxKeyTyped

    private void eidboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eidboxKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_eidboxKeyTyped

    private void n1boxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n1boxMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_n1boxMouseClicked

    private void suptableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suptableMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_suptableMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adrsbox;
    private javax.swing.JComboBox ccbox;
    private javax.swing.JComboBox countrybox;
    private javax.swing.JTextField eidbox;
    private javax.swing.JTextField faxbox;
    private javax.swing.JComboBox idbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField n1box;
    private javax.swing.JTextField n2box;
    private javax.swing.JComboBox namebox;
    private javax.swing.JTable suptable;
    // End of variables declaration//GEN-END:variables
}
