/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmpView;

import static java.lang.Short.valueOf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mycode.DBconnect;
/**
 *
 * @author User 1
 */
public class ATTENDENCE extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs=null;
    /**
     * Creates new form ATTENDENCE
     */
    public ATTENDENCE() {
        initComponents();
        
        
         this.setLocationRelativeTo(null);
       conn=DBconnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtempid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tekton Pro", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Attendance Tracker");

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Employee ID");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 0));
        jButton1.setText("In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtempid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtempid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setText("HOME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String eid = txtempid.getText();
//        String eid = txtempid.getText() +"_EMP";
        
        DateFormat dateFormat_date = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
        String s1 =dateFormat_date.format(date); //2014/08/06 15:59:48
        
        DateFormat dateFormat_month = new SimpleDateFormat("MM");
        Date month = new Date();
        String s2 =dateFormat_month.format(month); //2014/08/06 15:59:48
       
        DateFormat dateFormat_time_in = new SimpleDateFormat("HH:mm:ss");
        Date time = new Date();
        String s3 =dateFormat_time_in.format(time); //2014/08/06 15:59:48
        
        String s4=" ";
        String s5="0";
        
        
        if(eid.endsWith("EMP"))
        {
            try
        {
             String t="select * from employee where username='"+eid+"'";  
             pst=conn.prepareStatement(t);
             rs =pst.executeQuery();
             if(rs.next())
             {
                  try{
             
          
             
        String v="select * from dailyattendance where Employee_ID='"+eid+"' and Date='"+s1+"'";  
        pst=conn.prepareStatement(v);
        rs =pst.executeQuery();
        if(rs.next())
        {
            JOptionPane.showMessageDialog(null, "You have marked In Time for today.");
        }

        else{
            String x="INSERT INTO dailyattendance (Employee_ID,Month,Date,Time_In,Time_Out,Hours) VALUES ('"+eid+"','"+s2+"','"+s1+"','"+s3+"','"+s4+"','"+s5+"')";
            pst=conn.prepareStatement(x);
            pst.execute();
            
            }
             }
                
            
        catch(Exception e){

            System.out.println(e);
        }
        
        
         
            //  String y="INSERT INTO Rooms (cus_nic,deluxe,superior,premium,executive,total_price) values ('"+nic+"','"+Deluxe+"','"+Superior+"','"+Premium+"','"+Executive+"','"+total+"')";
            //  pst=con1.prepareStatement(y);
            //  pst.execute();

        }
             else
             {
                 JOptionPane.showMessageDialog(null, "Invalid ID");
             }

        
        }
        
        catch(Exception e)
        {
            System.out.println(e);
        }
       
        }
        
        else if(eid.endsWith("MGR"))
        {
            try
        {
             String t="select * from manager where username='"+eid+"'";  
             pst=conn.prepareStatement(t);
             rs =pst.executeQuery();
             if(rs.next())
             {
                  try{
             
          
             
        String v="select * from dailyattendance where Employee_ID='"+eid+"' and Date='"+s1+"'";  
        pst=conn.prepareStatement(v);
        rs =pst.executeQuery();
        if(rs.next())
        {
            JOptionPane.showMessageDialog(null, "You have marked In Time for today.");
        }

        else{
            String x="INSERT INTO dailyattendance (Employee_ID,Month,Date,Time_In,Time_Out,Hours) VALUES ('"+eid+"','"+s2+"','"+s1+"','"+s3+"','"+s4+"','"+s5+"')";
            pst=conn.prepareStatement(x);
            pst.execute();
            
            }
             }
                
            
        catch(Exception e){

            System.out.println(e);
        }
        
        
         
            //  String y="INSERT INTO Rooms (cus_nic,deluxe,superior,premium,executive,total_price) values ('"+nic+"','"+Deluxe+"','"+Superior+"','"+Premium+"','"+Executive+"','"+total+"')";
            //  pst=con1.prepareStatement(y);
            //  pst.execute();

        }
             
             else
             {
                 JOptionPane.showMessageDialog(null, "Invalid ID");
             }

        
        }
        
        catch(Exception e)
        {
            System.out.println(e);
        }
       
        }
        
        else
             {
                 JOptionPane.showMessageDialog(null, "Invalid ID");
             }
        
        
//DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                               
            String eid = txtempid.getText();
            
//        String eid = txtempid.getText()+"_EMP";
        
            DateFormat dateFormat_date = new SimpleDateFormat("yyyy/MM/dd");
            Date date = new Date();
            String s1 =dateFormat_date.format(date); //2014/08/06 15:59:48
            
            DateFormat dateFormat_month = new SimpleDateFormat("MM");
            Date month = new Date();
            String s2 =dateFormat_month.format(month); //2014/08/06 15:59:48
            
            DateFormat dateFormat_time_in = new SimpleDateFormat("HH:mm:ss");
            Date time = new Date();
            String s3 =dateFormat_time_in.format(time); //2014/08/06 15:59:48
          
             if(eid.endsWith("EMP"))
             {
                  try{ 
                     
                     String t="select * from employee where username='"+eid+"'";  
                     pst=conn.prepareStatement(t);
                     rs =pst.executeQuery();
                     
                     if(rs.next()){
                         
                         String v="select * from dailyattendance where Employee_ID='"+eid+"' and Date='"+s1+"'";  
                         pst=conn.prepareStatement(v);
                         rs =pst.executeQuery();
                     
                             if(rs.next())
                             {
                                 String x="00:00:00";
                                 v="select * from dailyattendance where Employee_ID='"+eid+"' and Time_Out='"+x+"' and Date='"+s1+"'";  
                                 pst=conn.prepareStatement(v);
                                 rs =pst.executeQuery();
                
                                        if(rs.next())
                                        {
                                         String s ="update dailyattendance set Time_Out='"+s3+"' where Date='"+s1+"' and Employee_ID='"+eid+"'";
                                         pst=conn.prepareStatement(s);
                                         pst.executeUpdate();
                
                                         String d ="update dailyattendance set Hours=TIMEDIFF(Time_Out,Time_In) where Date='"+s1+"' and Employee_ID='"+eid+"'";
                                         pst=conn.prepareStatement(d);
                                         pst.executeUpdate();
                     
                                         }
                
                                          else
                                          {
                                          JOptionPane.showMessageDialog(null, "You Have Marked Out Time Today");
                                          }
                   
                             }
                      
                             else
                             {
                                  JOptionPane.showMessageDialog(null, "Employee Is Absent Today");
                             }
                
             }
                      
             else
             {
                 JOptionPane.showMessageDialog(null, "Invalid ID");
             }
       }
                 
       catch(Exception e){
                System.out.println(e);
       }
            
        
             }
             
             else if(eid.endsWith("MGR"))
             {
                  try{ 
                     
                     String t="select * from manager where username='"+eid+"'";  
                     pst=conn.prepareStatement(t);
                     rs =pst.executeQuery();
                     
                     if(rs.next()){
                         
                         String v="select * from dailyattendance where Employee_ID='"+eid+"' and Date='"+s1+"'";  
                         pst=conn.prepareStatement(v);
                         rs =pst.executeQuery();
                     
                             if(rs.next())
                             {
                                 String x="00:00:00";
                                 v="select * from dailyattendance where Employee_ID='"+eid+"' and Time_Out='"+x+"' and Date='"+s1+"'";  
                                 pst=conn.prepareStatement(v);
                                 rs =pst.executeQuery();
                
                                        if(rs.next())
                                        {
                                         String s ="update dailyattendance set Time_Out='"+s3+"' where Date='"+s1+"' and Employee_ID='"+eid+"'";
                                         pst=conn.prepareStatement(s);
                                         pst.executeUpdate();
                
                                         String d ="update dailyattendance set Hours=TIMEDIFF(Time_Out,Time_In) where Date='"+s1+"' and Employee_ID='"+eid+"'";
                                         pst=conn.prepareStatement(d);
                                         pst.executeUpdate();
                     
                                         }
                
                                          else
                                          {
                                          JOptionPane.showMessageDialog(null, "You Have Marked Out Time Today");
                                          }
                   
                             }
                      
                             else
                             {
                                  JOptionPane.showMessageDialog(null, "Employee Is Absent Today");
                             }
                
             }
                      
             else
             {
                 JOptionPane.showMessageDialog(null, "Invalid ID");
             }
       }
                 
       catch(Exception e){
                System.out.println(e);
       }
             }
             else
             {
                 JOptionPane.showMessageDialog(null, "Invalid ID");
             }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       EMPLOYEE_VIEW_MAIN uss3;
        uss3 = new  EMPLOYEE_VIEW_MAIN();
        uss3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATTENDENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATTENDENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATTENDENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATTENDENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATTENDENCE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtempid;
    // End of variables declaration//GEN-END:variables
}
