/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmpView;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import mycode.DBconnect;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author User 1
 */
public class Leave extends javax.swing.JInternalFrame {
     private int userId;

    private String empType;

        
     Connection con = null;
     PreparedStatement pst = null;
     ResultSet rs = null;

    
    
    

    /**
     * Creates new form Leave
     */
    public Leave() {
        initComponents();
        
        
         con=DBconnect.connect();
      

        
        
        
    }
    Leave(int userId, String empType){
     try {

           initComponents();
            con = DBconnect.connect();
            this.userId = userId;
            this.empType = empType;
            
            if (empType.equals("EMP")) {
                String query = "select EmpID,Name,Age,Email,Address,Phone,Password,department "
                        + "from employee where EmpID=" + userId;

                pst = con.prepareStatement(query);
                rs = pst.executeQuery();
                while (rs.next()) {
                    
                    txtId1.setText(rs.getString("EmpID"));
                     txtemp1.setText(rs.getString("EmpID"));
                 
                    
                }
            }

        } catch (Exception e) {
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtreason = new javax.swing.JTextArea();
        jButton18 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dep = new javax.swing.JComboBox();
        fd1 = new com.toedter.calendar.JDateChooser();
        ed1 = new com.toedter.calendar.JDateChooser();
        txtId1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnstatus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        leavetable = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cnt = new javax.swing.JLabel();
        txtemp1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("LEAVES");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1030, 630));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1030, 630));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1030, 630));
        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentHidden(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.setMaximumSize(new java.awt.Dimension(1030, 630));
        jPanel3.setMinimumSize(new java.awt.Dimension(1030, 630));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Employee ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Leave Type");

        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Medical", "Casual", "Anual" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("From Date(yy/mm/dd)");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("End Date(yy/mm/dd)");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Reason");

        txtreason.setColumns(20);
        txtreason.setRows(5);
        jScrollPane2.setViewportView(txtreason);

        jButton18.setBackground(new java.awt.Color(0, 0, 0));
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("APPLY LEAVE");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Department");

        dep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "service station ", "filling station", " " }));

        txtId1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtId1.setForeground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(569, 569, 569))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ed1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(type, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dep, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fd1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtId1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(fd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)))
                .addGap(26, 26, 26)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("APPLY LEAVE", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1030, 630));
        jPanel2.setMinimumSize(new java.awt.Dimension(1030, 630));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Employee ID");

        btnstatus.setBackground(new java.awt.Color(0, 0, 0));
        btnstatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnstatus.setForeground(new java.awt.Color(255, 255, 255));
        btnstatus.setText("VIEW");
        btnstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstatusActionPerformed(evt);
            }
        });

        leavetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Leave ID", "Employee ID", "Department", "Type", "From Date", "End Date", "Reason", "Status"
            }
        ));
        leavetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leavetableMouseClicked(evt);
            }
        });
        leavetable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                leavetableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                leavetableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(leavetable);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PENDING", "APPROVED", "REJECTED" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("SELECT  LOAN STATUS");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("No of Leaves Applied");

        cnt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cnt.setForeground(new java.awt.Color(0, 102, 153));

        txtemp1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtemp1.setForeground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtemp1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(btnstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(jLabel13)
                                .addGap(43, 43, 43)
                                .addComponent(cnt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnstatus, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtemp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LEAVE HISTORY", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     boolean var1= false;
     boolean var2= false;
     boolean var3= false;
     
    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

        String id=txtId1.getText();
        String dep1=dep.getSelectedItem().toString();
        String ltype=type.getSelectedItem().toString();
        String reason=txtreason.getText();

        Date FD = fd1.getDate();
        String d1 =String.format("%1$tY-%1$tm-%1$td", FD);
       
        Date ED = ed1.getDate();
        String d2 =String.format("%1$tY-%1$tm-%1$td", ED);
       
        String sts="pending";

        
        
        
                      
                
        
 if(id.length()!=0 && dep1.length()!=0 && reason.length()!=0  && ltype.length()!=0  && d1.length()!=0 && d2.length()!=0  )
{
		var1 = true;
                
                
                
                
                
    if (id.matches("[0-9]+")) {
        var2 = true;

    } else {
        JOptionPane.showMessageDialog(null, "Employee ID is Incorrect!!!!  please check again!!");

    } 
    
    
    
              
    
    
    
   
                            
}
else 
{
	JOptionPane.showMessageDialog(null, "You haven't fill all the details. Please fill All!!!!");
}              
          
        
        
        
        
        
        
        
        
        
        
        
        
        
        
          if(var1 == true && var2 == true )
                  
                {
        
        
        
        
        try
        {

           // String q4 = "INSERT INTO leave(EmpID,Department,type,FromDate,EndDate,Reason,Status) VALUES ('"+id+"','"+dep1+"','"+ltype+"','"+d1+"','"+d2+"','"+reason+"','"+sts+"')";
       
                    String v11="select `Department` from `leave`  where  `EmpID`='"+id+"'";
                 pst=con.prepareStatement(v11);
                 rs =pst.executeQuery();
           
            if(rs.next())
            {
                String de1=rs.getString(1);
                
                if(de1.equalsIgnoreCase(dep1))
                {
                
                
             
            
          String q3=  "INSERT INTO `leave` ( `EmpID`, `Department`, `type`, `FromDate`, `EndDate`, `Reason`, `leave_Status`) VALUES ('"+id+"', '"+dep1+"', '"+ltype+"', '"+d1+"', '"+d2+"', '"+reason+"', '"+sts+"') ON DUPLICATE KEY UPDATE EmpID='"+id+"',  type='"+ltype+"', FromDate='"+d1+"', EndDate='"+d2+"',Reason='"+reason+"',leave_Status='"+sts+"' ";
          
           
                     // String q3=  "INSERT INTO `leave` ( `EmpID`, `Department`, `type`, `FromDate`, `EndDate`, `Reason`, `leave_Status`) VALUES ('"+id+"', '"+dep1+"', '"+ltype+"', '"+d1+"', '"+d2+"', '"+reason+"', '"+sts+"') ON DUPLICATE KEY UPDATE `EmpID`='"+id+"', `Department`='"+dep1+"', `type`='"+ltype+"', `FromDate`='"+d1+"', `EndDate`='"+d2+"', `Reason`='"+reason+"', `leave_Status`='"+sts+"' ";

            
            pst = con.prepareStatement(q3);
            pst.execute();

            
            
                
                JOptionPane.showMessageDialog(null, "You have successfully applied a leave!!!");
                
                }
                
                else{
                    
                    
                
                JOptionPane.showMessageDialog(null, "Department is incorrect!!!");
                
                    
                    
                }
            }
            
            
            
        }
        
        catch (Exception e)
        {
            System.out.println(e.getMessage());
        }

                }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void btnstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstatusActionPerformed
               String z=jComboBox1.getSelectedItem().toString();
             
                      String id=txtemp1.getText();

                      
        try{
//            String id=txtemp.getText();

           // String sql1 = " select Status  from leave where EmpID='"+id+"' ";

           String sql1=" SELECT `EmpID`, `Department`, `type`, `FromDate`, `EndDate`, `Reason`,`leave_Status` FROM `leave`WHERE `EmpID`='"+id+"' and `leave_Status`='"+z+"'";
            
            pst = con.prepareStatement(sql1);
            rs = pst.executeQuery();

            while (rs.next()) {
                 leavetable.setModel(DbUtils.resultSetToTableModel(rs));

//                txtstatus.setText(rs.getString("leave_Status"));

            }
        }
        catch(Exception e){

            System.out.println( e.getMessage());

        }

    }//GEN-LAST:event_btnstatusActionPerformed
    
    private void jTabbedPane1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1ComponentHidden

    private void leavetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavetableMouseClicked
               String id=txtemp1.getText();
            try{
         
         String v = "SELECT  count(`EmpID`) FROM `leave` WHERE `EmpID`= '"+id+"'  ";
                System.out.print(v);
//                    Statement selectStmt = con.createStatement();
//                    ResultSet rs = selectStmt.executeQuery(v);

                     pst = con.prepareStatement(v);
            rs= pst.executeQuery();
            
                    String Count = "";
                    
                    while (rs.next()) {
                       Count = rs.getString(1);
                        
                    }
               cnt.setText(Count);
         
         
        }
        catch(Exception e){
        
            System.out.println( e.getMessage());
            
        }
    }//GEN-LAST:event_leavetableMouseClicked

    private void leavetableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_leavetableKeyPressed
        //        int r = leavetable.getSelectedRow();
        //
        //        String LID1 = leavetable.getValueAt(r, 0).toString();
        //        String EmpID = leavetable.getValueAt(r, 1).toString();
        //        String DEP = leavetable.getValueAt(r, 2).toString();
        //        String type = leavetable.getValueAt(r, 3).toString();
        //        String fd1 = leavetable.getValueAt(r, 4).toString();
        //        String ed1 = leavetable.getValueAt(r, 5).toString();
        //
        //        String reason1 = leavetable.getValueAt(r, 6).toString();
        //        String status = leavetable.getValueAt(r, 7).toString();
        //
        //        LID.setText(LID1);
        //        ID.setText(EmpID);
        //        dep.setText(DEP);
        //        ltype.setText(type);
        //        fd.setText(fd1);
        //        ed.setText(ed1);
        //
        //        reason.setText(reason1);
        //        sts.setText(status);
    }//GEN-LAST:event_leavetableKeyPressed

    private void leavetableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_leavetableKeyReleased
        //        int r = leavetable.getSelectedRow();
        //
        //        String LID1 = leavetable.getValueAt(r, 0).toString();
        //        String EmpID = leavetable.getValueAt(r, 1).toString();
        //        String DEP = leavetable.getValueAt(r, 2).toString();
        //        String type = leavetable.getValueAt(r, 3).toString();
        //        String fd1 = leavetable.getValueAt(r, 4).toString();
        //        String ed1 = leavetable.getValueAt(r, 5).toString();
        //
        //        String reason1 = leavetable.getValueAt(r, 6).toString();
        //        String status = leavetable.getValueAt(r, 7).toString();
        //
        //        LID.setText(LID1);
        //        ID.setText(EmpID);
        //        dep.setText(DEP);
        //        ltype.setText(type);
        //        fd.setText(fd1);
        //        ed.setText(ed1);
        //
        //        reason.setText(reason1);
        //        sts.setText(status);
    }//GEN-LAST:event_leavetableKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnstatus;
    private javax.swing.JLabel cnt;
    private javax.swing.JComboBox dep;
    private com.toedter.calendar.JDateChooser ed1;
    private com.toedter.calendar.JDateChooser fd1;
    private javax.swing.JButton jButton18;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable leavetable;
    private javax.swing.JLabel txtId1;
    private javax.swing.JLabel txtemp1;
    private javax.swing.JTextArea txtreason;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables
}
