/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmpView;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import mycode.DBconnect;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author User 1
 */
public class LOANS extends javax.swing.JInternalFrame {

   private int userId;

    private String empType;

    
     Connection con = null;
     PreparedStatement pst = null;
     ResultSet rs = null;
    /**
     * Creates new form LOANS
     */
    public LOANS() {
        initComponents();
        
         con=DBconnect.connect();
    }
    LOANS(int userId, String empType){
          try {

           initComponents();
            con = DBconnect.connect();
            this.userId = userId;
            this.empType = empType;
            
            if (empType.equals("EMP")) {
                String query = "select EmpID,Name,Age,Email,Address,Phone,Password,department "
                        + "from employee where EmpID=" + userId;

                pst = con.prepareStatement(query);
                rs = pst.executeQuery();
                while (rs.next()) {
                    
                    txtId1.setText(rs.getString("EmpID"));
                   txtempid1.setText(rs.getString("EmpID"));
                    
                }
            }

        } catch (Exception e) {
        }
      
    }
    
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtReason = new javax.swing.JTextArea();
        btnApply = new javax.swing.JButton();
        txtDep = new javax.swing.JComboBox();
        txtId1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnview = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        loantable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        cnt = new javax.swing.JLabel();
        txtempid1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("LOANS");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1030, 630));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1030, 630));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1030, 630));
        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentHidden(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.setMaximumSize(new java.awt.Dimension(1030, 630));
        jPanel3.setMinimumSize(new java.awt.Dimension(1030, 630));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Employee ID");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Department");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Amount (Rs.)");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Reason");

        txtReason.setColumns(20);
        txtReason.setRows(5);
        jScrollPane2.setViewportView(txtReason);

        btnApply.setBackground(new java.awt.Color(0, 0, 0));
        btnApply.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnApply.setForeground(new java.awt.Color(255, 255, 255));
        btnApply.setText("APPLY LOAN");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        txtDep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "service station ", "filling station", " " }));

        txtId1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtId1.setForeground(new java.awt.Color(0, 102, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Date");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(155, 155, 155)))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDep, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(504, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2))
                    .addComponent(txtAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("APPLY LOAN", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1030, 630));
        jPanel2.setMinimumSize(new java.awt.Dimension(1030, 630));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Employee ID");

        btnview.setBackground(new java.awt.Color(0, 0, 0));
        btnview.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnview.setForeground(new java.awt.Color(255, 255, 255));
        btnview.setText("VIEW");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        loantable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Loan ID", "Employee ID", "Department", "Amount", "Reason", "Applied Date", "Status"
            }
        ));
        loantable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loantableMouseClicked(evt);
            }
        });
        loantable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loantableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loantableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(loantable);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("SELECT  LOAN STATUS");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PENDING", "APPROVED", "REJECTED" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("No of Loans Applied");

        cnt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cnt.setForeground(new java.awt.Color(0, 102, 153));

        txtempid1.setBackground(new java.awt.Color(51, 51, 0));
        txtempid1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtempid1.setForeground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(txtempid1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(btnview, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(jLabel13)
                                .addGap(35, 35, 35)
                                .addComponent(cnt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnview, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtempid1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LOAN HISTORY", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(871, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
               String z=jComboBox1.getSelectedItem().toString();
                
        String id=txtempid1.getText();
        try{

                   String sql = " select loanID,EmpID,Reason,Amount,Applied_Date,Status from loan where EmpID='"+id+"' and Status= '"+z+"'";
  
           pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
           loantable.setModel(DbUtils.resultSetToTableModel(rs));

           
         
         
           
           
           
           
           
           
           
           
           
        }
        
       catch(Exception e){
           
           System.out.println( e.getMessage());
           
       }
        

        
      
    }//GEN-LAST:event_btnviewActionPerformed

     boolean var1= false;
     boolean var2= false;
     boolean var3= false;
      
    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed

                String id=txtId1.getText();
                float Amount=0;

                String dep=txtDep.getSelectedItem().toString();
                String reason=txtReason.getText();
                String sts="PENDING";
               
  
  
        Date FD =date.getDate();
        String d1 =String.format("%1$tY-%1$tm-%1$td", FD);
            
   
         


 if(id.length()!=0 && dep.length()!=0 && reason.length()!=0  && d1.length()!=0)
{
		var1 = true;
                
                
                
                
                
    if (id.matches("[0-9]+")) {
        var2 = true;

    } else {
        JOptionPane.showMessageDialog(null, "Employee ID is Incorrect!!!!  please check again!!");

    } 
   
        Amount= Float.parseFloat(txtAmount.getText());  
        
        
        
                 
     
        
        
        
        
        
}
else 
{
	JOptionPane.showMessageDialog(null, "You haven't fill all the details. Please fill All!!!!");
}              
          
 
 
               if(var1 == true && var2 == true )
                  
                {
                    
                       try
                {
                        
                    
                    
                    
                    
                    String v11="select department from loan  where  EmpID='"+id+"'";
                 pst=con.prepareStatement(v11);
                 rs =pst.executeQuery();
           
                 System.out.println(v11);
                 
            if(rs.next())
            {
                String de1=rs.getString(1);
                
                if(de1.equalsIgnoreCase(dep))
                {
                
                
                    
                    
                    
                    
  String q3 = "INSERT INTO loan(EmpID,department,Amount,Reason,Applied_Date,Status) VALUES ('"+id+"','"+dep+"','"+Amount+"','"+reason+"','"+d1+"','"+sts+"')";     

                        
//                        String q3 = "INSERT INTO loan(EmpID,department,Amount,Reason,Status) VALUES ('"+id+"','"+dep+"','"+Amount+"','"+reason+"','"+sts+"')ON DUPLICATE KEY UPDATE department='"+dep+"', Amount='"+Amount+"', Reason='"+reason+"', Status='"+sts+"' ";     
                        pst = con.prepareStatement(q3);
                        pst.execute();
          
                System.out.println(q3);
                
                JOptionPane.showMessageDialog(null, "You have successfully applied a loan!!!");
                
                }
                
                else{
                
                JOptionPane.showMessageDialog(null, "Department is incorrect!!!!!!");
                }
                 
                  
                
            }  
        
                    
                    
                    
                    
                    
                    
                    
//                    
//                    
//                    
//                    
//  String q3 = "INSERT INTO loan(EmpID,department,Amount,Reason,Applied_Date,Status) VALUES ('"+id+"','"+dep+"','"+Amount+"','"+reason+"','"+d1+"','"+sts+"')";     
//
//                        
////                        String q3 = "INSERT INTO loan(EmpID,department,Amount,Reason,Status) VALUES ('"+id+"','"+dep+"','"+Amount+"','"+reason+"','"+sts+"')ON DUPLICATE KEY UPDATE department='"+dep+"', Amount='"+Amount+"', Reason='"+reason+"', Status='"+sts+"' ";     
//                        pst = con.prepareStatement(q3);
//                        pst.execute();
//          
//                
                }
                
                
                
                catch (Exception e)
                {
                        System.out.println(e.getMessage());
                    }
        
                   }
        
    }//GEN-LAST:event_btnApplyActionPerformed

    private void jTabbedPane1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1ComponentHidden

    private void loantableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loantableMouseClicked
        //        int r = loantable.getSelectedRow();
        //
        //        String LoanID = loantable.getValueAt(r, 0).toString();
        //        String EmpID = loantable.getValueAt(r, 1).toString();
        //        String DEP = loantable.getValueAt(r, 2).toString();
        //        String amt = loantable.getValueAt(r, 3).toString();
        //        String reason = loantable.getValueAt(r, 4).toString();
        //        String status = loantable.getValueAt(r, 5).toString();

        //        LID.setText(LoanID );
        //        ID.setText(EmpID);
        //        dept.setText(DEP);
        //        amount.setText(amt);
        //        resn.setText(reason);
        //        sts.setText(status);
        
        
          String id=txtempid1.getText();
          try{
            String v = "select COUNT(EmpID) from loan where EmpID='" + id+ "' ";
                System.out.print(v);
//                    Statement selectStmt = con.createStatement();
//                    ResultSet rs = selectStmt.executeQuery(v);

                     pst = con.prepareStatement(v);
            rs= pst.executeQuery();
            
                    String Count = "";
                    
                    while (rs.next()) {
                       Count = rs.getString(1);
                         
                    }
               cnt.setText(Count);
          }
          
          catch(Exception e){
          
            System.out.println( e.getMessage());

          }
        
        
    }//GEN-LAST:event_loantableMouseClicked

    private void loantableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loantableKeyPressed
        //        int r = loantable.getSelectedRow();
        //
        //        String LoanID = loantable.getValueAt(r, 0).toString();
        //        String EmpID = loantable.getValueAt(r, 1).toString();
        //        String DEP = loantable.getValueAt(r, 2).toString();
        //        String amt = loantable.getValueAt(r, 3).toString();
        //        String reason = loantable.getValueAt(r, 4).toString();
        //        String status = loantable.getValueAt(r, 5).toString();

        //        LID.setText(LoanID );
        //        ID.setText(EmpID);
        //        dept.setText(DEP);
        //        amount.setText(amt);
        //        resn.setText(reason);
        //        sts.setText(status);
    }//GEN-LAST:event_loantableKeyPressed

    private void loantableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loantableKeyReleased
        //        int r = loantable.getSelectedRow();
        //
        //        String LoanID = loantable.getValueAt(r, 0).toString();
        //        String EmpID = loantable.getValueAt(r, 1).toString();
        //        String DEP = loantable.getValueAt(r, 2).toString();
        //        String amt = loantable.getValueAt(r, 3).toString();
        //        String reason = loantable.getValueAt(r, 4).toString();
        //        String status = loantable.getValueAt(r, 5).toString();
        //
        //        LID.setText(LoanID );
        //        ID.setText(EmpID);
        //        dept.setText(DEP);
        //        amount.setText(amt);
        //        resn.setText(reason);
        //        sts.setText(status);
    }//GEN-LAST:event_loantableKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnview;
    private javax.swing.JLabel cnt;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable loantable;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JComboBox txtDep;
    private javax.swing.JLabel txtId1;
    private javax.swing.JTextArea txtReason;
    private javax.swing.JLabel txtempid1;
    // End of variables declaration//GEN-END:variables
}
